name: Build and Push Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build-And-Push-Frontend-Image-To-Docker-Hub:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-frontend-taskflow-image:${{ github.sha }}
          build-args: |
            DATABASE_URL=postgres://admin:secret@postgres-db:5432/postgres

      - name: Log out from DockerHub
        run: docker logout
