name: Deploy ws
on:
  push:
    branches:
      - master

jobs:
  Build-And-Push-Ws-Image-To-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-ws-taskflow-image:${{ github.sha }}

      - name: Log out from Docker Hub
        run: docker logout